### ISSUE TITLE
Memory leak in function `register_spi`

### ISSUE THREAD

**Issue by lizhuohua** [dovahcrow/xtp-rs#3]
In function `register_spi`, two raw pointers `trait_object_pointer` and `ptr` point to heap memory allocated by `Box`:
https://github.com/dovahcrow/xtp-rs/blob/8236eb6c76866d5a5806a56b57d33ab1b1175477/src/quote_api.rs#L133-L143

I think there is a memory leak because only `ptr` is freed when dropping:
https://github.com/dovahcrow/xtp-rs/blob/8236eb6c76866d5a5806a56b57d33ab1b1175477/src/quote_api.rs#L315-L322
https://github.com/dovahcrow/xtp-rs/blob/8236eb6c76866d5a5806a56b57d33ab1b1175477/src/bridge/bridge.hpp#L111

**Comment by dovahcrow** [comment]
@lizhuohua the trait_object_pointer is freed at here https://github.com/dovahcrow/xtp-rs/blob/8236eb6c76866d5a5806a56b57d33ab1b1175477/src/bridge/bridge.cpp#L432, after you called `delete stub` in `QuoteSpiStub_Destructor ` the destructor will be called and the destructor calls Drop::drop on the rust side.

**Comment by lizhuohua** [comment]
Thank you for your explanation, that makes sense!
